# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_attestations_rewards_response_data_ideal_rewards_inner import GetAttestationsRewardsResponseDataIdealRewardsInner
from models.get_attestations_rewards_response_data_total_rewards_inner import GetAttestationsRewardsResponseDataTotalRewardsInner


class AttestationsRewards(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AttestationsRewards - a model defined in OpenAPI

        ideal_rewards: The ideal_rewards of this AttestationsRewards.
        total_rewards: The total_rewards of this AttestationsRewards.
    """

    ideal_rewards: List[GetAttestationsRewardsResponseDataIdealRewardsInner] = Field(alias="ideal_rewards")
    total_rewards: List[GetAttestationsRewardsResponseDataTotalRewardsInner] = Field(alias="total_rewards")

AttestationsRewards.update_forward_refs()
