# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.beacon_block_all_of_body_attestations import BeaconBlockAllOfBodyAttestations
from models.beacon_block_all_of_body_attester_slashings import BeaconBlockAllOfBodyAttesterSlashings
from models.beacon_block_all_of_body_deposits import BeaconBlockAllOfBodyDeposits
from models.beacon_block_all_of_body_eth1_data import BeaconBlockAllOfBodyEth1Data
from models.beacon_block_all_of_body_proposer_slashings import BeaconBlockAllOfBodyProposerSlashings
from models.beacon_block_all_of_body_voluntary_exits import BeaconBlockAllOfBodyVoluntaryExits


class BeaconBlockAllOfBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BeaconBlockAllOfBody - a model defined in OpenAPI

        randao_reveal: The randao_reveal of this BeaconBlockAllOfBody [Optional].
        eth1_data: The eth1_data of this BeaconBlockAllOfBody [Optional].
        graffiti: The graffiti of this BeaconBlockAllOfBody [Optional].
        proposer_slashings: The proposer_slashings of this BeaconBlockAllOfBody [Optional].
        attester_slashings: The attester_slashings of this BeaconBlockAllOfBody [Optional].
        attestations: The attestations of this BeaconBlockAllOfBody [Optional].
        deposits: The deposits of this BeaconBlockAllOfBody [Optional].
        voluntary_exits: The voluntary_exits of this BeaconBlockAllOfBody [Optional].
    """

    randao_reveal: Optional[str] = Field(alias="randao_reveal", default=None)
    eth1_data: Optional[BeaconBlockAllOfBodyEth1Data] = Field(alias="eth1_data", default=None)
    graffiti: Optional[str] = Field(alias="graffiti", default=None)
    proposer_slashings: Optional[List[BeaconBlockAllOfBodyProposerSlashings]] = Field(alias="proposer_slashings", default=None)
    attester_slashings: Optional[List[BeaconBlockAllOfBodyAttesterSlashings]] = Field(alias="attester_slashings", default=None)
    attestations: Optional[List[BeaconBlockAllOfBodyAttestations]] = Field(alias="attestations", default=None)
    deposits: Optional[List[BeaconBlockAllOfBodyDeposits]] = Field(alias="deposits", default=None)
    voluntary_exits: Optional[List[BeaconBlockAllOfBodyVoluntaryExits]] = Field(alias="voluntary_exits", default=None)

    @validator("graffiti")
    def graffiti_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{64}$", value)
        return value

BeaconBlockAllOfBody.update_forward_refs()
