# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.beacon_block_all_of_body_data import BeaconBlockAllOfBodyData


class BeaconBlockAllOfBodyDeposits(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BeaconBlockAllOfBodyDeposits - a model defined in OpenAPI

        proof: The proof of this BeaconBlockAllOfBodyDeposits [Optional].
        data: The data of this BeaconBlockAllOfBodyDeposits [Optional].
    """

    proof: Optional[List[str]] = Field(alias="proof", default=None)
    data: Optional[BeaconBlockAllOfBodyData] = Field(alias="data", default=None)

BeaconBlockAllOfBodyDeposits.update_forward_refs()
