# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.beacon_block_all_of_body_attestation1 import BeaconBlockAllOfBodyAttestation1


class BeaconBlockAllOfBodyAttesterSlashings(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BeaconBlockAllOfBodyAttesterSlashings - a model defined in OpenAPI

        attestation_1: The attestation_1 of this BeaconBlockAllOfBodyAttesterSlashings [Optional].
        attestation_2: The attestation_2 of this BeaconBlockAllOfBodyAttesterSlashings [Optional].
    """

    attestation_1: Optional[BeaconBlockAllOfBodyAttestation1] = Field(alias="attestation_1", default=None)
    attestation_2: Optional[BeaconBlockAllOfBodyAttestation1] = Field(alias="attestation_2", default=None)

BeaconBlockAllOfBodyAttesterSlashings.update_forward_refs()
