# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class BeaconCommitteeSelectionRequestInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BeaconCommitteeSelectionRequestInner - a model defined in OpenAPI

        validator_index: The validator_index of this BeaconCommitteeSelectionRequestInner [Optional].
        slot: The slot of this BeaconCommitteeSelectionRequestInner [Optional].
        selection_proof: The selection_proof of this BeaconCommitteeSelectionRequestInner [Optional].
    """

    validator_index: Optional[str] = Field(alias="validator_index", default=None)
    slot: Optional[str] = Field(alias="slot", default=None)
    selection_proof: Optional[str] = Field(alias="selection_proof", default=None)

BeaconCommitteeSelectionRequestInner.update_forward_refs()
