# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.beacon_block_all_of_body_attestation1_data_source import BeaconBlockAllOfBodyAttestation1DataSource


class BeaconBlockAllOfBodyAttestation1Data(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BeaconBlockAllOfBodyAttestation1Data - a model defined in OpenAPI

        slot: The slot of this BeaconBlockAllOfBodyAttestation1Data [Optional].
        index: The index of this BeaconBlockAllOfBodyAttestation1Data [Optional].
        beacon_block_root: The beacon_block_root of this BeaconBlockAllOfBodyAttestation1Data [Optional].
        source: The source of this BeaconBlockAllOfBodyAttestation1Data [Optional].
        target: The target of this BeaconBlockAllOfBodyAttestation1Data [Optional].
    """

    slot: Optional[str] = Field(alias="slot", default=None)
    index: Optional[str] = Field(alias="index", default=None)
    beacon_block_root: Optional[str] = Field(alias="beacon_block_root", default=None)
    source: Optional[BeaconBlockAllOfBodyAttestation1DataSource] = Field(alias="source", default=None)
    target: Optional[BeaconBlockAllOfBodyAttestation1DataSource] = Field(alias="target", default=None)

BeaconBlockAllOfBodyAttestation1Data.update_forward_refs()
