# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.beacon_block_all_of_body_message import BeaconBlockAllOfBodyMessage


class BeaconBlockAllOfBodyVoluntaryExits(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BeaconBlockAllOfBodyVoluntaryExits - a model defined in OpenAPI

        message: The message of this BeaconBlockAllOfBodyVoluntaryExits [Optional].
        signature: The signature of this BeaconBlockAllOfBodyVoluntaryExits [Optional].
    """

    message: Optional[BeaconBlockAllOfBodyMessage] = Field(alias="message", default=None)
    signature: Optional[str] = Field(alias="signature", default=None)

    @validator("signature")
    def signature_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{192}$", value)
        return value

BeaconBlockAllOfBodyVoluntaryExits.update_forward_refs()
