# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of4_signed_blinded_blob_sidecars_inner_message import PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInnerMessage
from models.publish_blinded_block_request_one_of4_signed_blinded_block_message import PublishBlindedBlockRequestOneOf4SignedBlindedBlockMessage


class DenebBlindedBlockContents(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DenebBlindedBlockContents - a model defined in OpenAPI

        blinded_block: The blinded_block of this DenebBlindedBlockContents [Optional].
        blinded_blob_sidecars: The blinded_blob_sidecars of this DenebBlindedBlockContents [Optional].
    """

    blinded_block: Optional[PublishBlindedBlockRequestOneOf4SignedBlindedBlockMessage] = Field(alias="blinded_block", default=None)
    blinded_blob_sidecars: Optional[List[PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInnerMessage]] = Field(alias="blinded_blob_sidecars", default=None)

DenebBlindedBlockContents.update_forward_refs()
