# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_blinded_block_response_data import GetBlindedBlockResponseData


class GetBlindedBlockResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetBlindedBlockResponse - a model defined in OpenAPI

        version: The version of this GetBlindedBlockResponse [Optional].
        execution_optimistic: The execution_optimistic of this GetBlindedBlockResponse [Optional].
        finalized: The finalized of this GetBlindedBlockResponse [Optional].
        data: The data of this GetBlindedBlockResponse [Optional].
    """

    version: Optional[str] = Field(alias="version", default=None)
    execution_optimistic: Optional[bool] = Field(alias="execution_optimistic", default=None)
    finalized: Optional[bool] = Field(alias="finalized", default=None)
    data: Optional[GetBlindedBlockResponseData] = Field(alias="data", default=None)

GetBlindedBlockResponse.update_forward_refs()
