# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_block_request_one_of1_message_all_of_body_all_of_execution_payload_all_of_withdrawals_inner import PublishBlockRequestOneOf1MessageAllOfBodyAllOfExecutionPayloadAllOfWithdrawalsInner


class GetNextWithdrawalsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetNextWithdrawalsResponse - a model defined in OpenAPI

        execution_optimistic: The execution_optimistic of this GetNextWithdrawalsResponse [Optional].
        finalized: The finalized of this GetNextWithdrawalsResponse [Optional].
        data: The data of this GetNextWithdrawalsResponse [Optional].
    """

    execution_optimistic: Optional[bool] = Field(alias="execution_optimistic", default=None)
    finalized: Optional[bool] = Field(alias="finalized", default=None)
    data: Optional[List[PublishBlockRequestOneOf1MessageAllOfBodyAllOfExecutionPayloadAllOfWithdrawalsInner]] = Field(alias="data", default=None)

GetNextWithdrawalsResponse.update_forward_refs()
