# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetSyncCommitteeRewardsResponseDataInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetSyncCommitteeRewardsResponseDataInner - a model defined in OpenAPI

        validator_index: The validator_index of this GetSyncCommitteeRewardsResponseDataInner.
        reward: The reward of this GetSyncCommitteeRewardsResponseDataInner.
    """

    validator_index: str = Field(alias="validator_index")
    reward: str = Field(alias="reward")

GetSyncCommitteeRewardsResponseDataInner.update_forward_refs()
