# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_state_randao_response_data import GetStateRandaoResponseData


class GetStateRandaoResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetStateRandaoResponse - a model defined in OpenAPI

        execution_optimistic: The execution_optimistic of this GetStateRandaoResponse [Optional].
        finalized: The finalized of this GetStateRandaoResponse [Optional].
        data: The data of this GetStateRandaoResponse [Optional].
    """

    execution_optimistic: Optional[bool] = Field(alias="execution_optimistic", default=None)
    finalized: Optional[bool] = Field(alias="finalized", default=None)
    data: Optional[GetStateRandaoResponseData] = Field(alias="data", default=None)

GetStateRandaoResponse.update_forward_refs()
