# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_light_client_finality_update_response_data import GetLightClientFinalityUpdateResponseData


class GetLightClientFinalityUpdateResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetLightClientFinalityUpdateResponse - a model defined in OpenAPI

        version: The version of this GetLightClientFinalityUpdateResponse [Optional].
        data: The data of this GetLightClientFinalityUpdateResponse [Optional].
    """

    version: Optional[str] = Field(alias="version", default=None)
    data: Optional[GetLightClientFinalityUpdateResponseData] = Field(alias="data", default=None)

GetLightClientFinalityUpdateResponse.update_forward_refs()
