# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of import PublishBlindedBlockRequestOneOf
from models.publish_blinded_block_request_one_of1 import PublishBlindedBlockRequestOneOf1
from models.publish_blinded_block_request_one_of2 import PublishBlindedBlockRequestOneOf2
from models.publish_blinded_block_request_one_of3 import PublishBlindedBlockRequestOneOf3
from models.publish_blinded_block_request_one_of4_signed_blinded_block import PublishBlindedBlockRequestOneOf4SignedBlindedBlock
from models.publish_blinded_block_request_one_of4_signed_blinded_block_message import PublishBlindedBlockRequestOneOf4SignedBlindedBlockMessage


class GetBlindedBlockResponseData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetBlindedBlockResponseData - a model defined in OpenAPI

        message: The message of this GetBlindedBlockResponseData [Optional].
        signature: The signature of this GetBlindedBlockResponseData [Optional].
    """

    message: Optional[PublishBlindedBlockRequestOneOf4SignedBlindedBlockMessage] = Field(alias="message", default=None)
    signature: Optional[str] = Field(alias="signature", default=None)

    @validator("signature")
    def signature_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{192}$", value)
        return value

GetBlindedBlockResponseData.update_forward_refs()
