# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetBlockRewardsResponseData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetBlockRewardsResponseData - a model defined in OpenAPI

        proposer_index: The proposer_index of this GetBlockRewardsResponseData [Optional].
        total: The total of this GetBlockRewardsResponseData [Optional].
        attestations: The attestations of this GetBlockRewardsResponseData [Optional].
        sync_aggregate: The sync_aggregate of this GetBlockRewardsResponseData [Optional].
        proposer_slashings: The proposer_slashings of this GetBlockRewardsResponseData [Optional].
        attester_slashings: The attester_slashings of this GetBlockRewardsResponseData [Optional].
    """

    proposer_index: Optional[str] = Field(alias="proposer_index", default=None)
    total: Optional[str] = Field(alias="total", default=None)
    attestations: Optional[str] = Field(alias="attestations", default=None)
    sync_aggregate: Optional[str] = Field(alias="sync_aggregate", default=None)
    proposer_slashings: Optional[str] = Field(alias="proposer_slashings", default=None)
    attester_slashings: Optional[str] = Field(alias="attester_slashings", default=None)

GetBlockRewardsResponseData.update_forward_refs()
