# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetAttestationsRewardsResponseDataTotalRewardsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetAttestationsRewardsResponseDataTotalRewardsInner - a model defined in OpenAPI

        validator_index: The validator_index of this GetAttestationsRewardsResponseDataTotalRewardsInner.
        head: The head of this GetAttestationsRewardsResponseDataTotalRewardsInner.
        target: The target of this GetAttestationsRewardsResponseDataTotalRewardsInner.
        source: The source of this GetAttestationsRewardsResponseDataTotalRewardsInner.
        inclusion_delay: The inclusion_delay of this GetAttestationsRewardsResponseDataTotalRewardsInner [Optional].
        inactivity: The inactivity of this GetAttestationsRewardsResponseDataTotalRewardsInner.
    """

    validator_index: str = Field(alias="validator_index")
    head: str = Field(alias="head")
    target: str = Field(alias="target")
    source: str = Field(alias="source")
    inclusion_delay: Optional[str] = Field(alias="inclusion_delay", default=None)
    inactivity: str = Field(alias="inactivity")

GetAttestationsRewardsResponseDataTotalRewardsInner.update_forward_refs()
