# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_sync_committee_rewards_response_data_inner import GetSyncCommitteeRewardsResponseDataInner


class GetSyncCommitteeRewardsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetSyncCommitteeRewardsResponse - a model defined in OpenAPI

        execution_optimistic: The execution_optimistic of this GetSyncCommitteeRewardsResponse [Optional].
        finalized: The finalized of this GetSyncCommitteeRewardsResponse [Optional].
        data: The data of this GetSyncCommitteeRewardsResponse [Optional].
    """

    execution_optimistic: Optional[bool] = Field(alias="execution_optimistic", default=None)
    finalized: Optional[bool] = Field(alias="finalized", default=None)
    data: Optional[List[GetSyncCommitteeRewardsResponseDataInner]] = Field(alias="data", default=None)

GetSyncCommitteeRewardsResponse.update_forward_refs()
