# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_fork_choice_response_fork_choice_nodes_inner import GetForkChoiceResponseForkChoiceNodesInner
from models.get_state_finality_checkpoints_response_data_previous_justified import GetStateFinalityCheckpointsResponseDataPreviousJustified


class GetForkChoiceResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetForkChoiceResponse - a model defined in OpenAPI

        justified_checkpoint: The justified_checkpoint of this GetForkChoiceResponse.
        finalized_checkpoint: The finalized_checkpoint of this GetForkChoiceResponse.
        fork_choice_nodes: The fork_choice_nodes of this GetForkChoiceResponse [Optional].
        extra_data: The extra_data of this GetForkChoiceResponse [Optional].
    """

    justified_checkpoint: GetStateFinalityCheckpointsResponseDataPreviousJustified = Field(alias="justified_checkpoint")
    finalized_checkpoint: GetStateFinalityCheckpointsResponseDataPreviousJustified = Field(alias="finalized_checkpoint")
    fork_choice_nodes: Optional[List[GetForkChoiceResponseForkChoiceNodesInner]] = Field(alias="fork_choice_nodes", default=None)
    extra_data: Optional[Dict[str, Any]] = Field(alias="extra_data", default=None)

GetForkChoiceResponse.update_forward_refs()
