# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetVersionResponseData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetVersionResponseData - a model defined in OpenAPI

        version: The version of this GetVersionResponseData [Optional].
    """

    version: Optional[str] = Field(alias="version", default=None)

GetVersionResponseData.update_forward_refs()
