# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of3_message_all_of_body_all_of_bls_to_execution_changes_inner import PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInner


class GetPoolBLSToExecutionChangesResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetPoolBLSToExecutionChangesResponse - a model defined in OpenAPI

        data: The data of this GetPoolBLSToExecutionChangesResponse [Optional].
    """

    data: Optional[List[PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInner]] = Field(alias="data", default=None)

GetPoolBLSToExecutionChangesResponse.update_forward_refs()
