# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_block_headers_response_data_inner import GetBlockHeadersResponseDataInner


class GetBlockHeadersResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetBlockHeadersResponse - a model defined in OpenAPI

        execution_optimistic: The execution_optimistic of this GetBlockHeadersResponse [Optional].
        finalized: The finalized of this GetBlockHeadersResponse [Optional].
        data: The data of this GetBlockHeadersResponse [Optional].
    """

    execution_optimistic: Optional[bool] = Field(alias="execution_optimistic", default=None)
    finalized: Optional[bool] = Field(alias="finalized", default=None)
    data: Optional[List[GetBlockHeadersResponseDataInner]] = Field(alias="data", default=None)

GetBlockHeadersResponse.update_forward_refs()
