# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetStateV2ResponseDataOneOf3HistoricalSummariesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetStateV2ResponseDataOneOf3HistoricalSummariesInner - a model defined in OpenAPI

        block_summary_root: The block_summary_root of this GetStateV2ResponseDataOneOf3HistoricalSummariesInner [Optional].
        state_summary_root: The state_summary_root of this GetStateV2ResponseDataOneOf3HistoricalSummariesInner [Optional].
    """

    block_summary_root: Optional[str] = Field(alias="block_summary_root", default=None)
    state_summary_root: Optional[str] = Field(alias="state_summary_root", default=None)

    @validator("block_summary_root")
    def block_summary_root_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{64}$", value)
        return value

    @validator("state_summary_root")
    def state_summary_root_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{64}$", value)
        return value

GetStateV2ResponseDataOneOf3HistoricalSummariesInner.update_forward_refs()
