# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.get_block_headers_response_data_inner_header_message import GetBlockHeadersResponseDataInnerHeaderMessage
from models.publish_blinded_block_request_one_of3_message_all_of_body_all_of_execution_payload_header import PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfExecutionPayloadHeader


class GetLightClientBootstrapResponseDataOneOf1Header(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetLightClientBootstrapResponseDataOneOf1Header - a model defined in OpenAPI

        beacon: The beacon of this GetLightClientBootstrapResponseDataOneOf1Header [Optional].
        execution: The execution of this GetLightClientBootstrapResponseDataOneOf1Header [Optional].
        execution_branch: The execution_branch of this GetLightClientBootstrapResponseDataOneOf1Header [Optional].
    """

    beacon: Optional[GetBlockHeadersResponseDataInnerHeaderMessage] = Field(alias="beacon", default=None)
    execution: Optional[PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfExecutionPayloadHeader] = Field(alias="execution", default=None)
    execution_branch: Optional[List[str]] = Field(alias="execution_branch", default=None)

GetLightClientBootstrapResponseDataOneOf1Header.update_forward_refs()
