# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PostLivenessResponseBodyDataInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PostLivenessResponseBodyDataInner - a model defined in OpenAPI

        index: The index of this PostLivenessResponseBodyDataInner [Optional].
        is_live: The is_live of this PostLivenessResponseBodyDataInner [Optional].
    """

    index: Optional[str] = Field(alias="index", default=None)
    is_live: Optional[bool] = Field(alias="is_live", default=None)

PostLivenessResponseBodyDataInner.update_forward_refs()
