# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.post_liveness_response_body_data_inner import PostLivenessResponseBodyDataInner


class PostLivenessResponseBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PostLivenessResponseBody - a model defined in OpenAPI

        data: The data of this PostLivenessResponseBody [Optional].
    """

    data: Optional[List[PostLivenessResponseBodyDataInner]] = Field(alias="data", default=None)

PostLivenessResponseBody.update_forward_refs()
