# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.produce_block_v3_response_data_one_of import ProduceBlockV3ResponseDataOneOf
from models.produce_block_v3_response_data_one_of1 import ProduceBlockV3ResponseDataOneOf1
from models.publish_blinded_block_request_one_of4_signed_blinded_blob_sidecars_inner_message import PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInnerMessage
from models.publish_blinded_block_request_one_of4_signed_blinded_block_message import PublishBlindedBlockRequestOneOf4SignedBlindedBlockMessage
from models.publish_block_request_one_of2_signed_blob_sidecars_inner_message import PublishBlockRequestOneOf2SignedBlobSidecarsInnerMessage
from models.publish_block_request_one_of2_signed_block_message import PublishBlockRequestOneOf2SignedBlockMessage


class ProduceBlockV3ResponseData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ProduceBlockV3ResponseData - a model defined in OpenAPI

        block: The block of this ProduceBlockV3ResponseData [Optional].
        blob_sidecars: The blob_sidecars of this ProduceBlockV3ResponseData [Optional].
        blinded_block: The blinded_block of this ProduceBlockV3ResponseData [Optional].
        blinded_blob_sidecars: The blinded_blob_sidecars of this ProduceBlockV3ResponseData [Optional].
    """

    block: Optional[PublishBlockRequestOneOf2SignedBlockMessage] = Field(alias="block", default=None)
    blob_sidecars: Optional[List[PublishBlockRequestOneOf2SignedBlobSidecarsInnerMessage]] = Field(alias="blob_sidecars", default=None)
    blinded_block: Optional[PublishBlindedBlockRequestOneOf4SignedBlindedBlockMessage] = Field(alias="blinded_block", default=None)
    blinded_blob_sidecars: Optional[List[PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInnerMessage]] = Field(alias="blinded_blob_sidecars", default=None)

ProduceBlockV3ResponseData.update_forward_refs()
