# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInnerMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInnerMessage - a model defined in OpenAPI

        validator_index: The validator_index of this PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInnerMessage [Optional].
        from_bls_pubkey: The from_bls_pubkey of this PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInnerMessage [Optional].
        to_execution_address: The to_execution_address of this PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInnerMessage [Optional].
    """

    validator_index: Optional[str] = Field(alias="validator_index", default=None)
    from_bls_pubkey: Optional[str] = Field(alias="from_bls_pubkey", default=None)
    to_execution_address: Optional[str] = Field(alias="to_execution_address", default=None)

    @validator("from_bls_pubkey")
    def from_bls_pubkey_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{96}$", value)
        return value

    @validator("to_execution_address")
    def to_execution_address_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{40}$", value)
        return value

PublishBlindedBlockRequestOneOf3MessageAllOfBodyAllOfBlsToExecutionChangesInnerMessage.update_forward_refs()
