# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of import PublishBlindedBlockRequestOneOf
from models.publish_blinded_block_request_one_of1 import PublishBlindedBlockRequestOneOf1
from models.publish_blinded_block_request_one_of2 import PublishBlindedBlockRequestOneOf2
from models.publish_blinded_block_request_one_of3 import PublishBlindedBlockRequestOneOf3
from models.publish_blinded_block_request_one_of3_message import PublishBlindedBlockRequestOneOf3Message
from models.publish_blinded_block_request_one_of4 import PublishBlindedBlockRequestOneOf4
from models.publish_blinded_block_request_one_of4_signed_blinded_blob_sidecars_inner import PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInner
from models.publish_blinded_block_request_one_of4_signed_blinded_block import PublishBlindedBlockRequestOneOf4SignedBlindedBlock


class PublishBlindedBlockRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublishBlindedBlockRequest - a model defined in OpenAPI

        message: The message of this PublishBlindedBlockRequest [Optional].
        signature: The signature of this PublishBlindedBlockRequest [Optional].
        signed_blinded_block: The signed_blinded_block of this PublishBlindedBlockRequest [Optional].
        signed_blinded_blob_sidecars: The signed_blinded_blob_sidecars of this PublishBlindedBlockRequest [Optional].
    """

    message: Optional[PublishBlindedBlockRequestOneOf3Message] = Field(alias="message", default=None)
    signature: Optional[str] = Field(alias="signature", default=None)
    signed_blinded_block: Optional[PublishBlindedBlockRequestOneOf4SignedBlindedBlock] = Field(alias="signed_blinded_block", default=None)
    signed_blinded_blob_sidecars: Optional[List[PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInner]] = Field(alias="signed_blinded_blob_sidecars", default=None)

    @validator("signature")
    def signature_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{192}$", value)
        return value

PublishBlindedBlockRequest.update_forward_refs()
