# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of_message_all_of_body_deposits_inner_data import PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInnerData


class PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInner - a model defined in OpenAPI

        proof: The proof of this PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInner [Optional].
        data: The data of this PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInner [Optional].
    """

    proof: Optional[List[str]] = Field(alias="proof", default=None)
    data: Optional[PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInnerData] = Field(alias="data", default=None)

PublishBlindedBlockRequestOneOfMessageAllOfBodyDepositsInner.update_forward_refs()
