# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of4_signed_blinded_blob_sidecars_inner import PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInner
from models.publish_blinded_block_request_one_of4_signed_blinded_block import PublishBlindedBlockRequestOneOf4SignedBlindedBlock


class PublishBlindedBlockRequestOneOf4(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublishBlindedBlockRequestOneOf4 - a model defined in OpenAPI

        signed_blinded_block: The signed_blinded_block of this PublishBlindedBlockRequestOneOf4 [Optional].
        signed_blinded_blob_sidecars: The signed_blinded_blob_sidecars of this PublishBlindedBlockRequestOneOf4 [Optional].
    """

    signed_blinded_block: Optional[PublishBlindedBlockRequestOneOf4SignedBlindedBlock] = Field(alias="signed_blinded_block", default=None)
    signed_blinded_blob_sidecars: Optional[List[PublishBlindedBlockRequestOneOf4SignedBlindedBlobSidecarsInner]] = Field(alias="signed_blinded_blob_sidecars", default=None)

PublishBlindedBlockRequestOneOf4.update_forward_refs()
