# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.publish_blinded_block_request_one_of import PublishBlindedBlockRequestOneOf
from models.publish_blinded_block_request_one_of1 import PublishBlindedBlockRequestOneOf1
from models.publish_block_request_one_of import PublishBlockRequestOneOf
from models.publish_block_request_one_of1 import PublishBlockRequestOneOf1
from models.publish_block_request_one_of1_message import PublishBlockRequestOneOf1Message
from models.publish_block_request_one_of2 import PublishBlockRequestOneOf2
from models.publish_block_request_one_of2_signed_blob_sidecars_inner import PublishBlockRequestOneOf2SignedBlobSidecarsInner
from models.publish_block_request_one_of2_signed_block import PublishBlockRequestOneOf2SignedBlock


class PublishBlockRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublishBlockRequest - a model defined in OpenAPI

        message: The message of this PublishBlockRequest [Optional].
        signature: The signature of this PublishBlockRequest [Optional].
        signed_block: The signed_block of this PublishBlockRequest [Optional].
        signed_blob_sidecars: The signed_blob_sidecars of this PublishBlockRequest [Optional].
    """

    message: Optional[PublishBlockRequestOneOf1Message] = Field(alias="message", default=None)
    signature: Optional[str] = Field(alias="signature", default=None)
    signed_block: Optional[PublishBlockRequestOneOf2SignedBlock] = Field(alias="signed_block", default=None)
    signed_blob_sidecars: Optional[List[PublishBlockRequestOneOf2SignedBlobSidecarsInner]] = Field(alias="signed_blob_sidecars", default=None)

    @validator("signature")
    def signature_pattern(cls, value):
        assert value is not None and re.match(r"^0x[a-fA-F0-9]{192}$", value)
        return value

PublishBlockRequest.update_forward_refs()
